FROM alpine as builder

RUN set -x \
	&& apk add --update ca-certificates curl

# RUN set -x \
#   && wget https://github.com/nats-io/natscli/releases/download/v0.0.35/nats-0.0.35-linux-amd64.zip \
#  && unzip nats-0.0.35-linux-amd64.zip \
#   && mv nats-0.0.35-linux-amd64/nats /bin \
#   && rm -rf  nats-0.0.35-linux-amd64.zip nats-0.0.35-linux-amd64 \
#   && nats --version

RUN set -x \
  && wget https://github.com/oras-project/oras/releases/download/v0.16.0/oras_0.16.0_linux_amd64.tar.gz \
  && mkdir -p oras-install/ \
  && tar -zxf oras_0.16.0_*.tar.gz -C oras-install/ \
  && mv oras-install/oras /bin/ \
  && rm -rf oras_0.16.0_*.tar.gz oras-install/

RUN set -x \
	&& curl -fsSL https://dl.k8s.io/v1.25.2/kubernetes-client-linux-amd64.tar.gz | tar -zxv \
    && mv /kubernetes/client/bin/kubectl /usr/bin/kubectl

RUN set -x \
  && wget https://github.com/segmentio/kubectl-curl/releases/download/v0.1.5/kubectl-curl_v0.1.5_linux_amd64.tar.gz \
  && mkdir -p curl-install/ \
  && tar -zxf kubectl-curl_v0.1.5_linux_amd64.tar.gz -C curl-install/ \
  && mv curl-install/kubectl-curl_v0.1.5_linux_amd64 /usr/bin/kubectl-curl \
  && rm -rf kubectl-curl_v0.1.5_linux_amd64.tar.gz curl-install/


